services:
  front:
    container_name: front
    image: lorainep/cityzen:latest
    restart: unless-stopped
    volumes:
      - ./project_data:/data
    networks :
      - front
    env_file:
      - .env


networks:
  front:
    external: true