services:
  front:
    container_name: front
    image: lorainep/citydo:latest
    restart: unless-stopped

    networks :
      - front

    # si build local 
    # env_file:
    # - .env


networks:
  front:
    external: true