services:
  # front
  front:
    container_name: front
    image: lorainep/cityzen:latest
    restart: unless-stopped
    ports:
      - '4443:443'
      - '8080:80'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./project_data:/data
    networks :
      - front
    env_file:
      - .env


networks:
  front:
    external: true