name: Build and Deploy Front-End App

on:
    push:
        branches: [main]

jobs:
    build_and_deploy_front:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build and push Docker image
              uses: docker/build-push-action@v5
              with:
                  context: .
                  push: true
                  tags: |
                      lorainep/citydo:latest
                      lorainep/citydo:${{ github.sha }}
                  cache-from: type=gha
                  cache-to: type=gha,mode=max
                  build-args:
                      | # Passer les variables VITE_* via les secrets GitHub
                      VITE_FETCH_URL=${{ secrets.VITE_FETCH_URL }}
                      VITE_APP_URL=${{ secrets.VITE_APP_URL }}
                      VITE_STORE_KEY=${{ secrets.VITE_STORE_KEY }}
                      VITE_DOMAIN=${{ secrets.VITE_DOMAIN }}
                      VITE_WS_URL=${{ secrets.VITE_WS_URL }}

            - name: Trigger Portainer Deploy Webhook (Front-End)
              run: curl -s -X POST ${{ secrets.PORTAINER_WEBHOOK_URL }}
